---
dist: xenial
addons: { apt: { packages: [ debootstrap ] } }
language: generic
env:
  - DIST=potato  ARCH=i386
  - DIST=woody   ARCH=i386
  - DIST=sarge   ARCH=i386
  - DIST=etch    ARCH=i386
  - DIST=etch    ARCH=i386  VARIANT=minbase
  - DIST=etch    ARCH=amd64
  - DIST=etch    ARCH=amd64 VARIANT=minbase
  - DIST=lenny   ARCH=i386
  - DIST=lenny   ARCH=i386  VARIANT=minbase
  - DIST=lenny   ARCH=amd64
  - DIST=lenny   ARCH=amd64 VARIANT=minbase
  - DIST=squeeze ARCH=i386
  - DIST=squeeze ARCH=i386  VARIANT=minbase
  - DIST=squeeze ARCH=amd64
  - DIST=squeeze ARCH=amd64 VARIANT=minbase
  - DIST=wheezy  ARCH=i386
  - DIST=wheezy  ARCH=i386  VARIANT=minbase
  - DIST=wheezy  ARCH=amd64
  - DIST=wheezy  ARCH=amd64 VARIANT=minbase
  - DIST=jessie  ARCH=i386
  - DIST=jessie  ARCH=i386  VARIANT=minbase
  - DIST=jessie  ARCH=amd64
  - DIST=jessie  ARCH=amd64 VARIANT=minbase
  - DIST=stretch ARCH=i386
  - DIST=stretch ARCH=i386  VARIANT=minbase
  - DIST=stretch ARCH=amd64
  - DIST=stretch ARCH=amd64 VARIANT=minbase
script:
  - IMAGE="$DOCKERHUB_USERNAME/debian-${DIST}-${ARCH}"
  - ARGS=()
  - if [ -n "$VARIANT" ]; then ARGS+=("-t" "$VARIANT"); IMAGE+="-$VARIANT"; fi
  - ./docker-create-debian-image -i "$IMAGE" "${ARGS[@]}" "$DIST" "$ARCH"
jobs:
  include:
    - name: omnilint
      env: [ OMNILINT=true ]
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
before_deploy:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
deploy:
  - provider: script
    script: docker push "$IMAGE"
    on:
      condition: $OMNILINT != true
