---
dist: xenial
addons: { apt: { packages: [ debootstrap, qemu-user-static ] } }
language: generic
env:
  - V=2.2 DIST=potato  ARCH=alpha
  - V=2.2 DIST=potato  ARCH=arm
  - V=2.2 DIST=potato  ARCH=i386
  # V=2.2 DIST=potato  ARCH=m68k # Invalid instruction: https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465551
  # V=2.2 DIST=potato  ARCH=powerpc # travis timeout: https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465552
  # V=2.2 DIST=potato  ARCH=sparc # travis timeout: https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465553
  - V=3.0 DIST=woody   ARCH=alpha
  # V=3.0 DIST=woody   ARCH=arm # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465555
  # V=3.0 DIST=woody   ARCH=hppa # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465556
  - V=3.0 DIST=woody   ARCH=i386
  # V=3.0 DIST=woody   ARCH=ia64 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465558
  # V=3.0 DIST=woody   ARCH=m68k # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465559
  # V=3.0 DIST=woody   ARCH=mips # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465560
  # V=3.0 DIST=woody   ARCH=mipsel # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465561
  # V=3.0 DIST=woody   ARCH=powerpc # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465562
  # V=3.0 DIST=woody   ARCH=s390 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465563
  # V=3.0 DIST=woody   ARCH=sparc # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465564
  - V=3.1 DIST=sarge   ARCH=alpha
  - V=3.1 DIST=sarge   ARCH=arm
  # V=3.1 DIST=sarge   ARCH=hppa # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465567
  - V=3.1 DIST=sarge   ARCH=i386
  # V=3.1 DIST=sarge   ARCH=ia64 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465570
  # V=3.1 DIST=sarge   ARCH=m68k # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465571
  - V=3.1 DIST=sarge   ARCH=mips
  - V=3.1 DIST=sarge   ARCH=mipsel
  - V=3.1 DIST=sarge   ARCH=powerpc
  # V=3.1 DIST=sarge   ARCH=s390 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465575
  # V=3.1 DIST=sarge   ARCH=sparc https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465576
  - V=4.0 DIST=etch    ARCH=alpha
  - V=4.0 DIST=etch    ARCH=alpha VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=amd64
  - V=4.0 DIST=etch    ARCH=amd64 VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=arm
  - V=4.0 DIST=etch    ARCH=arm VARIANT=minbase
  # V=4.0 DIST=etch    ARCH=hppa # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465583
  # V=4.0 DIST=etch    ARCH=hppa VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465584
  - V=4.0 DIST=etch    ARCH=i386
  - V=4.0 DIST=etch    ARCH=i386 VARIANT=minbase
  # V=4.0 DIST=etch    ARCH=ia64 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465587
  # V=4.0 DIST=etch    ARCH=ia64 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465588
  - V=4.0 DIST=etch    ARCH=mips
  - V=4.0 DIST=etch    ARCH=mipsel
  - V=4.0 DIST=etch    ARCH=mipsel VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=mips VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=powerpc
  - V=4.0 DIST=etch    ARCH=powerpc VARIANT=minbase
  # V=4.0 DIST=etch    ARCH=s390 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465595
  # V=4.0 DIST=etch    ARCH=s390 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465596
  # V=4.0 DIST=etch    ARCH=sparc # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465597
  # V=4.0 DIST=etch    ARCH=sparc VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465598
  - V=5.0 DIST=lenny   ARCH=alpha
  - V=5.0 DIST=lenny   ARCH=alpha VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=amd64
  - V=5.0 DIST=lenny   ARCH=amd64 VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=arm
  - V=5.0 DIST=lenny   ARCH=armel
  - V=5.0 DIST=lenny   ARCH=armel VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=arm VARIANT=minbase
  # V=5.0 DIST=lenny   ARCH=hppa # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465612
  # V=5.0 DIST=lenny   ARCH=hppa VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465613
  - V=5.0 DIST=lenny   ARCH=i386
  - V=5.0 DIST=lenny   ARCH=i386 VARIANT=minbase
  # V=5.0 DIST=lenny   ARCH=ia64 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465617
  # V=5.0 DIST=lenny   ARCH=ia64 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465618
  - V=5.0 DIST=lenny   ARCH=mips
  - V=5.0 DIST=lenny   ARCH=mipsel
  - V=5.0 DIST=lenny   ARCH=mipsel VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=mips VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=powerpc
  - V=5.0 DIST=lenny   ARCH=powerpc VARIANT=minbase
  # V=5.0 DIST=lenny   ARCH=s390 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465625
  # V=5.0 DIST=lenny   ARCH=s390 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465626
  # V=5.0 DIST=lenny   ARCH=sparc # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465627
  # V=5.0 DIST=lenny   ARCH=sparc VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465628
  - V=6.0 DIST=squeeze ARCH=amd64
  - V=6.0 DIST=squeeze ARCH=amd64 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=armel
  - V=6.0 DIST=squeeze ARCH=armel VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=i386
  - V=6.0 DIST=squeeze ARCH=i386 VARIANT=minbase
  # V=6.0 DIST=squeeze ARCH=ia64 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465639
  # V=6.0 DIST=squeeze ARCH=ia64 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465640
  - V=6.0 DIST=squeeze ARCH=mips
  - V=6.0 DIST=squeeze ARCH=mipsel
  - V=6.0 DIST=squeeze ARCH=mipsel VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=mips VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=powerpc
  - V=6.0 DIST=squeeze ARCH=powerpc VARIANT=minbase
  # V=6.0 DIST=squeeze ARCH=s390 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465651
  # V=6.0 DIST=squeeze ARCH=s390 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465653
  # V=6.0 DIST=squeeze ARCH=sparc # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465654
  # V=6.0 DIST=squeeze ARCH=sparc VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465655
  - V=7   DIST=wheezy  ARCH=amd64
  - V=7   DIST=wheezy  ARCH=amd64 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=armel
  - V=7   DIST=wheezy  ARCH=armel VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=armhf
  - V=7   DIST=wheezy  ARCH=armhf VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=i386
  - V=7   DIST=wheezy  ARCH=i386 VARIANT=minbase
  # V=7   DIST=wheezy  ARCH=ia64 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465664
  # V=7   DIST=wheezy  ARCH=ia64 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465665
  - V=7   DIST=wheezy  ARCH=mips
  - V=7   DIST=wheezy  ARCH=mipsel
  - V=7   DIST=wheezy  ARCH=mipsel VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=mips VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=powerpc
  - V=7   DIST=wheezy  ARCH=powerpc VARIANT=minbase
  # V=7   DIST=wheezy  ARCH=s390 # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465677
  # V=7   DIST=wheezy  ARCH=s390 VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465678
  - V=7   DIST=wheezy  ARCH=s390x
  - V=7   DIST=wheezy  ARCH=s390x VARIANT=minbase
  # V=7   DIST=wheezy  ARCH=sparc # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465681
  # V=7   DIST=wheezy  ARCH=sparc VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465682
  - V=8   DIST=jessie  ARCH=amd64
  - V=8   DIST=jessie  ARCH=amd64 VARIANT=minbase
  - V=8   DIST=jessie  ARCH=arm64
  - V=8   DIST=jessie  ARCH=arm64 VARIANT=minbase
  - V=8   DIST=jessie  ARCH=armel
  - V=8   DIST=jessie  ARCH=armel VARIANT=minbase
  - V=8   DIST=jessie  ARCH=armhf
  - V=8   DIST=jessie  ARCH=armhf VARIANT=minbase
  - V=8   DIST=jessie  ARCH=i386
  - V=8   DIST=jessie  ARCH=i386 VARIANT=minbase
  - V=8   DIST=jessie  ARCH=mips
  - V=8   DIST=jessie  ARCH=mipsel
  - V=8   DIST=jessie  ARCH=mipsel VARIANT=minbase
  - V=8   DIST=jessie  ARCH=mips VARIANT=minbase
  - V=8   DIST=jessie  ARCH=powerpc
  - V=8   DIST=jessie  ARCH=powerpc VARIANT=minbase
  - V=8   DIST=jessie  ARCH=ppc64el
  - V=8   DIST=jessie  ARCH=ppc64el VARIANT=minbase
  - V=8   DIST=jessie  ARCH=s390x
  - V=8   DIST=jessie  ARCH=s390x VARIANT=minbase
  - V=9   DIST=stretch ARCH=amd64
  - V=9   DIST=stretch ARCH=amd64 VARIANT=minbase
  - V=9   DIST=stretch ARCH=arm64
  - V=9   DIST=stretch ARCH=arm64 VARIANT=minbase
  # V=9   DIST=stretch ARCH=armel # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465708
  - V=9   DIST=stretch ARCH=armel VARIANT=minbase
  # V=9   DIST=stretch ARCH=armhf # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465712
  - V=9   DIST=stretch ARCH=armhf VARIANT=minbase
  - V=9   DIST=stretch ARCH=i386
  - V=9   DIST=stretch ARCH=i386 VARIANT=minbase
  - V=9   DIST=stretch ARCH=mips
  # V=9   DIST=stretch ARCH=mips64el # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465718
  # V=9   DIST=stretch ARCH=mips64el VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465719
  - V=9   DIST=stretch ARCH=mipsel
  - V=9   DIST=stretch ARCH=mipsel VARIANT=minbase
  - V=9   DIST=stretch ARCH=mips VARIANT=minbase
  # V=9   DIST=stretch ARCH=ppc64el # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465723
  # V=9   DIST=stretch ARCH=ppc64el VARIANT=minbase # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465724
  # V=9   DIST=stretch ARCH=s390x # https://travis-ci.com/lpenz/docker-debian-releases/jobs/164465725
  - V=9   DIST=stretch ARCH=s390x VARIANT=minbase
script:
  - MIRROR=debian
  - IMAGE="$DOCKERHUB_USERNAME/debian-${DIST}-${ARCH}"
  - ARGS=()
  - if [ "$ARCH" != "i386" ] && [ "$ARCH" != "amd64" ]; then ARGS+=("-q"); fi
  - if [ -n "$VARIANT" ]; then ARGS+=("-t" "$VARIANT"); IMAGE+="-$VARIANT"; fi
  - ./docker-create-debian-image -m "$MIRROR" -i "$IMAGE" "${ARGS[@]}" "$DIST" "$ARCH"
before_deploy:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
deploy:
  - provider: script
    script: docker push "$IMAGE"
    on:
      branch: debian
