---
dist: xenial
language: generic
jobs:
  include:
    - name: build image
      addons: { apt: { packages: [ debootstrap, qemu-user-static ] } }
      script: ./travis-script.sh
      if: branch ~= .*-.*
    - name: build scripts
      addons: { apt: { packages: [ scons, golang ] } }
      script:
        - go get golang.org/x/net/html
        - scons
      if: NOT branch ~= .*-.*
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
      if: NOT branch ~= .*-.*
