---
addons: { apt: { packages: [ debootstrap ] } }
language: generic
env:
  - ARCH=i386  DIST=potato
  - ARCH=i386  DIST=woody
  - ARCH=i386  DIST=sarge
  - ARCH=i386  DIST=etch
  - ARCH=amd64 DIST=etch
  - ARCH=i386  DIST=lenny
  - ARCH=amd64 DIST=lenny
  - ARCH=i386  DIST=squeeze
  - ARCH=amd64 DIST=squeeze
  - ARCH=i386  DIST=wheezy
  - ARCH=amd64 DIST=wheezy
  - ARCH=i386  DIST=jessie
  - ARCH=amd64 DIST=jessie
  - ARCH=i386  DIST=stretch
  - ARCH=amd64 DIST=stretch
script:
  - ./docker-create-debian-image "$DIST" "$ARCH"
jobs:
  include:
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
