---
dist: xenial
addons: { apt: { packages: [ debootstrap, qemu-user-static ] } }
language: generic
# Only some basic specific tests on master;
# the official build is done in branches.
env:
  - MIRROR=ubuntu V=16.04 DIST=xenial  ARCH=armhf
  - MIRROR=debian V=9     DIST=stretch ARCH=mipsel VARIANT=minbase
script: ./travis-script.sh
jobs:
  include:
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
