---
dist: xenial
addons: { apt: { packages: [ debootstrap, qemu-user-static ] } }
language: generic
env:
  - V=2.2 DIST=potato  ARCH=alpha
  - V=2.2 DIST=potato  ARCH=arm
  - V=2.2 DIST=potato  ARCH=i386
  - V=2.2 DIST=potato  ARCH=m68k
  - V=2.2 DIST=potato  ARCH=powerpc
  - V=2.2 DIST=potato  ARCH=sparc
  - V=3.0 DIST=woody   ARCH=alpha
  - V=3.0 DIST=woody   ARCH=arm
  - V=3.0 DIST=woody   ARCH=hppa
  - V=3.0 DIST=woody   ARCH=i386
  - V=3.0 DIST=woody   ARCH=ia64
  - V=3.0 DIST=woody   ARCH=m68k
  - V=3.0 DIST=woody   ARCH=mips
  - V=3.0 DIST=woody   ARCH=mipsel
  - V=3.0 DIST=woody   ARCH=powerpc
  - V=3.0 DIST=woody   ARCH=s390
  - V=3.0 DIST=woody   ARCH=sparc
  - V=3.1 DIST=sarge   ARCH=alpha
  - V=3.1 DIST=sarge   ARCH=arm
  - V=3.1 DIST=sarge   ARCH=hppa
  - V=3.1 DIST=sarge   ARCH=i386
  - V=3.1 DIST=sarge   ARCH=ia64
  - V=3.1 DIST=sarge   ARCH=m68k
  - V=3.1 DIST=sarge   ARCH=mips
  - V=3.1 DIST=sarge   ARCH=mipsel
  - V=3.1 DIST=sarge   ARCH=powerpc
  - V=3.1 DIST=sarge   ARCH=s390
  - V=3.1 DIST=sarge   ARCH=sparc
  - V=4.0 DIST=etch    ARCH=alpha
  - V=4.0 DIST=etch    ARCH=alpha VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=amd64
  - V=4.0 DIST=etch    ARCH=amd64 VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=arm
  - V=4.0 DIST=etch    ARCH=arm VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=hppa
  - V=4.0 DIST=etch    ARCH=hppa VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=i386
  - V=4.0 DIST=etch    ARCH=i386 VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=ia64
  - V=4.0 DIST=etch    ARCH=ia64 VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=mips
  - V=4.0 DIST=etch    ARCH=mipsel
  - V=4.0 DIST=etch    ARCH=mipsel VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=mips VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=powerpc
  - V=4.0 DIST=etch    ARCH=powerpc VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=s390
  - V=4.0 DIST=etch    ARCH=s390 VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=sparc
  - V=4.0 DIST=etch    ARCH=sparc VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=udeb
  - V=4.0 DIST=etch    ARCH=udeb-nf
  - V=4.0 DIST=etch    ARCH=udeb-nf VARIANT=minbase
  - V=4.0 DIST=etch    ARCH=udeb VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=alpha
  - V=5.0 DIST=lenny   ARCH=alpha VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=amd64
  - V=5.0 DIST=lenny   ARCH=amd64 VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=arm
  - V=5.0 DIST=lenny   ARCH=armel
  - V=5.0 DIST=lenny   ARCH=armel VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=arm VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=hppa
  - V=5.0 DIST=lenny   ARCH=hppa VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=i386
  - V=5.0 DIST=lenny   ARCH=i386 VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=ia64
  - V=5.0 DIST=lenny   ARCH=ia64 VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=mips
  - V=5.0 DIST=lenny   ARCH=mipsel
  - V=5.0 DIST=lenny   ARCH=mipsel VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=mips VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=powerpc
  - V=5.0 DIST=lenny   ARCH=powerpc VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=s390
  - V=5.0 DIST=lenny   ARCH=s390 VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=sparc
  - V=5.0 DIST=lenny   ARCH=sparc VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=udeb
  - V=5.0 DIST=lenny   ARCH=udeb-nf
  - V=5.0 DIST=lenny   ARCH=udeb-nf VARIANT=minbase
  - V=5.0 DIST=lenny   ARCH=udeb VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=amd64
  - V=6.0 DIST=squeeze ARCH=amd64 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=armel
  - V=6.0 DIST=squeeze ARCH=armel VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=i386
  - V=6.0 DIST=squeeze ARCH=i386 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=ia64
  - V=6.0 DIST=squeeze ARCH=ia64 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=kfreebsd-amd64
  - V=6.0 DIST=squeeze ARCH=kfreebsd-amd64 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=kfreebsd-i386
  - V=6.0 DIST=squeeze ARCH=kfreebsd-i386 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=mips
  - V=6.0 DIST=squeeze ARCH=mipsel
  - V=6.0 DIST=squeeze ARCH=mipsel VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=mips VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=powerpc
  - V=6.0 DIST=squeeze ARCH=powerpc VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=s390
  - V=6.0 DIST=squeeze ARCH=s390 VARIANT=minbase
  - V=6.0 DIST=squeeze ARCH=sparc
  - V=6.0 DIST=squeeze ARCH=sparc VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=amd64
  - V=7   DIST=wheezy  ARCH=amd64 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=armel
  - V=7   DIST=wheezy  ARCH=armel VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=armhf
  - V=7   DIST=wheezy  ARCH=armhf VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=i386
  - V=7   DIST=wheezy  ARCH=i386 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=ia64
  - V=7   DIST=wheezy  ARCH=ia64 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=kfreebsd-amd64
  - V=7   DIST=wheezy  ARCH=kfreebsd-amd64 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=kfreebsd-i386
  - V=7   DIST=wheezy  ARCH=kfreebsd-i386 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=mips
  - V=7   DIST=wheezy  ARCH=mipsel
  - V=7   DIST=wheezy  ARCH=mipsel VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=mips VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=powerpc
  - V=7   DIST=wheezy  ARCH=powerpc VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=s390
  - V=7   DIST=wheezy  ARCH=s390 VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=s390x
  - V=7   DIST=wheezy  ARCH=s390x VARIANT=minbase
  - V=7   DIST=wheezy  ARCH=sparc
  - V=7   DIST=wheezy  ARCH=sparc VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-amd64
  #  - V=7   DIST=wheezy  ARCH=udeb-amd64 VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-armel
  #  - V=7   DIST=wheezy  ARCH=udeb-armel VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-armhf
  #  - V=7   DIST=wheezy  ARCH=udeb-armhf VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-i386
  #  - V=7   DIST=wheezy  ARCH=udeb-i386 VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-ia64
  #  - V=7   DIST=wheezy  ARCH=udeb-ia64 VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-kfreebsd-amd64
  #  - V=7   DIST=wheezy  ARCH=udeb-kfreebsd-amd64 VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-kfreebsd-i386
  #  - V=7   DIST=wheezy  ARCH=udeb-kfreebsd-i386 VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-mips
  #  - V=7   DIST=wheezy  ARCH=udeb-mipsel
  #  - V=7   DIST=wheezy  ARCH=udeb-mipsel VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-mips VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-powerpc
  #  - V=7   DIST=wheezy  ARCH=udeb-powerpc VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-s390
  #  - V=7   DIST=wheezy  ARCH=udeb-s390 VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-s390x
  #  - V=7   DIST=wheezy  ARCH=udeb-s390x VARIANT=minbase
  #  - V=7   DIST=wheezy  ARCH=udeb-sparc
  #  - V=7   DIST=wheezy  ARCH=udeb-sparc VARIANT=minbase
  - V=8   DIST=jessie  ARCH=amd64
  - V=8   DIST=jessie  ARCH=amd64 VARIANT=minbase
  - V=8   DIST=jessie  ARCH=arm64
  - V=8   DIST=jessie  ARCH=arm64 VARIANT=minbase
  - V=8   DIST=jessie  ARCH=armel
  - V=8   DIST=jessie  ARCH=armel VARIANT=minbase
  - V=8   DIST=jessie  ARCH=armhf
  - V=8   DIST=jessie  ARCH=armhf VARIANT=minbase
  - V=8   DIST=jessie  ARCH=i386
  - V=8   DIST=jessie  ARCH=i386 VARIANT=minbase
  - V=8   DIST=jessie  ARCH=mips
  - V=8   DIST=jessie  ARCH=mipsel
  - V=8   DIST=jessie  ARCH=mipsel VARIANT=minbase
  - V=8   DIST=jessie  ARCH=mips VARIANT=minbase
  - V=8   DIST=jessie  ARCH=powerpc
  - V=8   DIST=jessie  ARCH=powerpc VARIANT=minbase
  - V=8   DIST=jessie  ARCH=ppc64el
  - V=8   DIST=jessie  ARCH=ppc64el VARIANT=minbase
  - V=8   DIST=jessie  ARCH=s390x
  - V=8   DIST=jessie  ARCH=s390x VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-amd64
  #  - V=8   DIST=jessie  ARCH=udeb-amd64 VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-arm64
  #  - V=8   DIST=jessie  ARCH=udeb-arm64 VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-armel
  #  - V=8   DIST=jessie  ARCH=udeb-armel VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-armhf
  #  - V=8   DIST=jessie  ARCH=udeb-armhf VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-i386
  #  - V=8   DIST=jessie  ARCH=udeb-i386 VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-mips
  #  - V=8   DIST=jessie  ARCH=udeb-mipsel
  #  - V=8   DIST=jessie  ARCH=udeb-mipsel VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-mips VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-powerpc
  #  - V=8   DIST=jessie  ARCH=udeb-powerpc VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-ppc64el
  #  - V=8   DIST=jessie  ARCH=udeb-ppc64el VARIANT=minbase
  #  - V=8   DIST=jessie  ARCH=udeb-s390x
  #  - V=8   DIST=jessie  ARCH=udeb-s390x VARIANT=minbase
  - V=9   DIST=stretch ARCH=amd64
  - V=9   DIST=stretch ARCH=amd64 VARIANT=minbase
  - V=9   DIST=stretch ARCH=arm64
  - V=9   DIST=stretch ARCH=arm64 VARIANT=minbase
  - V=9   DIST=stretch ARCH=armel
  - V=9   DIST=stretch ARCH=armel VARIANT=minbase
  - V=9   DIST=stretch ARCH=armhf
  - V=9   DIST=stretch ARCH=armhf VARIANT=minbase
  - V=9   DIST=stretch ARCH=i386
  - V=9   DIST=stretch ARCH=i386 VARIANT=minbase
  - V=9   DIST=stretch ARCH=mips
  - V=9   DIST=stretch ARCH=mips64el
  - V=9   DIST=stretch ARCH=mips64el VARIANT=minbase
  - V=9   DIST=stretch ARCH=mipsel
  - V=9   DIST=stretch ARCH=mipsel VARIANT=minbase
  - V=9   DIST=stretch ARCH=mips VARIANT=minbase
  - V=9   DIST=stretch ARCH=ppc64el
  - V=9   DIST=stretch ARCH=ppc64el VARIANT=minbase
  - V=9   DIST=stretch ARCH=s390x
  - V=9   DIST=stretch ARCH=s390x VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-amd64
  #  - V=9   DIST=stretch ARCH=udeb-amd64 VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-arm64
  #  - V=9   DIST=stretch ARCH=udeb-arm64 VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-armel
  #  - V=9   DIST=stretch ARCH=udeb-armel VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-armhf
  #  - V=9   DIST=stretch ARCH=udeb-armhf VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-i386
  #  - V=9   DIST=stretch ARCH=udeb-i386 VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-mips
  #  - V=9   DIST=stretch ARCH=udeb-mips64el
  #  - V=9   DIST=stretch ARCH=udeb-mips64el VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-mipsel
  #  - V=9   DIST=stretch ARCH=udeb-mipsel VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-mips VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-ppc64el
  #  - V=9   DIST=stretch ARCH=udeb-ppc64el VARIANT=minbase
  #  - V=9   DIST=stretch ARCH=udeb-s390x
  #  - V=9   DIST=stretch ARCH=udeb-s390x VARIANT=minbase
script:
  - IMAGE="$DOCKERHUB_USERNAME/debian-${DIST}-${ARCH}"
  - ARGS=()
  - if [ "$ARCH" != "i386" ] && [ "$ARCH" != "amd64" ] && [ "$ARCH" != "ia64" ]; then ARGS+=("-q"); fi
  - if [ -n "$VARIANT" ]; then ARGS+=("-t" "$VARIANT"); IMAGE+="-$VARIANT"; fi
  - ./docker-create-debian-image -i "$IMAGE" "${ARGS[@]}" "$DIST" "$ARCH"
jobs:
  include:
    - name: omnilint
      env: [ OMNILINT=true ]
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
before_deploy:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
deploy:
  - provider: script
    script: docker push "$IMAGE"
    on:
      condition: $OMNILINT != true
