---
dist: xenial
language: generic
jobs:
  include:
    - name: build image
      addons: { apt: { packages: [ debootstrap, qemu-user-static ] } }
      script:
        - ./travis-script.sh _image.txt
        - . _image.txt
      if: branch ~= .*-.*
    - name: build scripts and check README.md
      addons: { apt: { packages: [ scons, golang ] } }
      script:
        - go get golang.org/x/net/html
        - scons
        - git diff
      if: NOT branch ~= .*-.*
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
      if: NOT branch ~= .*-.*
before_deploy:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
deploy:
  - provider: script
    script: docker push "$IMAGE"
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ .*-.*
