---
dist: xenial
language: generic
jobs:
  include:
    - name: build image
      addons: { apt: { packages: [ debootstrap, qemu-user-static, golang, scons ] } }
      install:
        - sudo cp -Rd debootstrap_scripts/* /usr/share/debootstrap/scripts/
      script:
        - go get golang.org/x/net/html
        - scons dockerhub-set-descriptions
        - while sleep 9m; do echo "=====[ ping ]====="; done &
        - PING_PID="$!"
        - ./travis-script.sh _image.txt
        - kill "$PING_PID"
        - cat _image.txt
        - . _image.txt
        - export IMAGE DESCRIPTION
      if: branch ~= .*-.*
    - name: build scripts and check README.md
      addons: { apt: { packages: [ scons, golang ] } }
      script:
        - go get golang.org/x/net/html
        - scons
        - git diff
      if: NOT branch ~= .*-.*
    - name: omnilint
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
      if: NOT branch ~= .*-.*
before_deploy:
  - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis-deploy.sh
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ .*-.*
